insert into subjects values("C");
insert into subjects values("UNIX");
insert into subjects values("Technology");
insert into subjects values("Go");
insert into subjects values("Science Fiction");
insert into subjects values("Productivity");
insert into subjects values("Psychology");
insert into subjects values("Politics");
insert into subjects values("History");
insert into books values ("The C Programming Language",1);      
insert into books values ("The Go Programming Language",1);  
insert into books values ("The UNIX Programming Environment",1);
insert into books values ("Cryptonomicon",2);     
insert into books values ("Deep Work",3);
insert into books values ("Atomic Habits",4);   
insert into books values ("The City and The City",5);   
insert into books values ("The Great War for Civilisation",6); 
insert into publisher values("PHI","India");
insert into publisher values("Harper","USA");
insert into publisher values("GCP","USA");
insert into publisher values("Avery","USA");
insert into publisher values("Del Rey","UK");
insert into publisher values("Vintage","UK");
insert into books_subjects values(1,1);
insert into books_subjects values(1,2);
insert into books_subjects values(1,3);
insert into books_subjects values(2,3);
insert into books_subjects values(2,4);
insert into books_subjects values(3,2);
insert into books_subjects values(3,3);
insert into books_subjects values(4,3);
insert into books_subjects values(4,5);
insert into books_subjects values(5,3);
insert into books_subjects values(5,6);
insert into books_subjects values(6,6);
insert into books_subjects values(6,7);
insert into books_subjects values(7,5);
insert into books_subjects values(7,8);
insert into books_subjects values(8,8);
insert into books_subjects values(8,9);
